export const CURRENCY_CODE: { [key: string]: string } = {
  AE: "د.إ",
  AF: "؋",
  AL: "L",
  AM: "֏",
  NL: "ƒ",
  AO: "Kz",
  AR: "$",
  AU: "A$",
  AW: "ƒ",
  AZ: "₼",
  BA: "KM",
  BB: "Bds$",
  BD: "৳",
  BG: "лв",
  BH: ".د.ب",
  BI: "FBu",
  BM: "$",
  BN: "B$",
  BO: "Bs.",
  BR: "R$",
  BS: "B$",
  BT: "Nu.",
  BW: "P",
  BY: "Br",
  BZ: "BZ$",
  CA: "C$",
  CD: "FC",
  CH: "Fr",
  CL: "CLP$",
  CN: "¥",
  CO: "COL$",
  CR: "₡",
  CU: "$",
  CV: "Esc",
  CZ: "Kč",
  DJ: "Fdj",
  DK: "kr",
  DO: "RD$",
  DZ: "دج",
  EG: "£",
  ER: "Nfk",
  ET: "Br",
  EU: "€",
  FJ: "FJ$",
  FK: "£",
  FO: "kr",
  GB: "£",
  GE: "₾",
  GG: "£",
  GH: "₵",
  GI: "£",
  GM: "D",
  GN: "FG",
  GT: "Q",
  GY: "GY$",
  HK: "HK$",
  HN: "L",
  HR: "kn",
  HT: "G",
  HU: "Ft",
  ID: "Rp",
  IL: "₪",
  IM: "£",
  IN: "₹",
  IQ: "ع.د",
  IR: "﷼",
  IS: "kr",
  JE: "£",
  JM: "J$",
  JO: "د.ا",
  JP: "¥",
  KE: "KSh",
  KG: "с",
  KH: "៛",
  KI: "$",
  KM: "CF",
  KR: "₩",
  KW: "د.ك",
  KY: "KY$",
  KZ: "₸",
  LA: "₭",
  LB: "ل.ل",
  LK: "Rs",
  LR: "L$",
  LS: "L",
  LY: "ل.د",
  MA: "د.م.",
  MD: "L",
  MG: "Ar",
  MK: "ден",
  MM: "K",
  MN: "₮",
  MO: "MOP$",
  MR: "UM",
  MU: "₨",
  MV: "Rf",
  MW: "MK",
  MX: "Mex$",
  MY: "RM",
  MZ: "MT",
  NA: "N$",
  NG: "₦",
  NI: "C$",
  NO: "kr",
  NP: "Rs",
  NZ: "NZ$",
  OM: "ر.ع.",
  PA: "B/.",
  PE: "S/",
  PG: "K",
  PH: "₱",
  PK: "₨",
  PL: "zł",
  PY: "₲",
  QA: "ر.ق",
  RO: "lei",
  RS: "дин.",
  RU: "₽",
  RW: "FRw",
  SA: "﷼",
  SB: "SI$",
  SC: "₨",
  SD: "ج.س.",
  SE: "kr",
  SG: "S$",
  SH: "£",
  SL: "Le",
  SO: "Sh",
  SR: "SR$",
  SS: "£",
  ST: "Db",
  SY: "£",
  SZ: "E",
  TH: "฿",
  TJ: "ЅМ",
  TM: "T",
  TN: "د.ت",
  TO: "T$",
  TR: "₺",
  TT: "TT$",
  TV: "$",
  TW: "NT$",
  TZ: "TSh",
  UA: "₴",
  UG: "USh",
  US: "$",
  UY: "UY$",
  UZ: "so'm",
  VE: "Bs.",
  VN: "₫",
  VU: "VT",
  WS: "T",
  XAF: "FCFA",
  XCD: "EC$",
  XOF: "CFA",
  XPF: "₣",
  YE: "﷼",
  ZA: "R",
  ZM: "ZK",
  ZW: "Z$",
};

export const COUNTRY_ISO_CODE_2: { [key: string]: string } = {
  AFGHANISTAN: "AF",
  ALBANIA: "AL",
  ALGERIA: "DZ",
  "AMERICAN SAMOA": "AS",
  ANDORRA: "AD",
  ANGOLA: "AO",
  ANGUILLA: "AI",
  ANTARCTICA: "AQ",
  "ANTIGUA AND BARBUDA": "AG",
  ARGENTINA: "AR",
  ARMENIA: "AM",
  ARUBA: "AW",
  AUSTRALIA: "AU",
  AUSTRIA: "AT",
  AZERBAIJAN: "AZ",
  BAHAMAS: "BS",
  BAHRAIN: "BH",
  BANGLADESH: "BD",
  BARBADOS: "BB",
  BELARUS: "BY",
  BELGIUM: "BE",
  BELIZE: "BZ",
  BENIN: "BJ",
  BERMUDA: "BM",
  BHUTAN: "BT",
  BOLIVIA: "BO",
  "BOSNIA AND HERZEGOVINA": "BA",
  BOTSWANA: "BW",
  BRAZIL: "BR",
  "BRITISH INDIAN OCEAN TERRITORY": "IO",
  "BRITISH VIRGIN ISLANDS": "VG",
  BRUNEI: "BN",
  BULGARIA: "BG",
  "BURKINA FASO": "BF",
  BURUNDI: "BI",
  CAMBODIA: "KH",
  CAMEROON: "CM",
  CANADA: "CA",
  "CAPE VERDE": "CV",
  "CAYMAN ISLANDS": "KY",
  "CENTRAL AFRICAN REPUBLIC": "CF",
  CHAD: "TD",
  CHILE: "CL",
  CHINA: "CN",
  "CHRISTMAS ISLAND": "CX",
  "COCOS ISLANDS": "CC",
  COLOMBIA: "CO",
  COMOROS: "KM",
  "COOK ISLANDS": "CK",
  "COSTA RICA": "CR",
  CROATIA: "HR",
  CUBA: "CU",
  CURACAO: "CW",
  CYPRUS: "CY",
  "CZECH REPUBLIC": "CZ",
  "DEMOCRATIC REPUBLIC OF THE CONGO": "CD",
  DENMARK: "DK",
  DJIBOUTI: "DJ",
  DOMINICA: "DM",
  "DOMINICAN REPUBLIC": "DO",
  "EAST TIMOR": "TL",
  ECUADOR: "EC",
  EGYPT: "EG",
  "EL SALVADOR": "SV",
  "EQUATORIAL GUINEA": "GQ",
  ERITREA: "ER",
  ESTONIA: "EE",
  ETHIOPIA: "ET",
  "FALKLAND ISLANDS": "FK",
  "FAROE ISLANDS": "FO",
  FIJI: "FJ",
  FINLAND: "FI",
  FRANCE: "FR",
  "FRENCH POLYNESIA": "PF",
  GABON: "GA",
  GAMBIA: "GM",
  GEORGIA: "GE",
  GERMANY: "DE",
  GHANA: "GH",
  GIBRALTAR: "GI",
  GREECE: "GR",
  GREENLAND: "GL",
  GRENADA: "GD",
  GUAM: "GU",
  GUATEMALA: "GT",
  GUERNSEY: "GG",
  GUINEA: "GN",
  "GUINEA-BISSAU": "GW",
  GUYANA: "GY",
  HAITI: "HT",
  HONDURAS: "HN",
  "HONG KONG": "HK",
  HUNGARY: "HU",
  ICELAND: "IS",
  INDIA: "IN",
  INDONESIA: "ID",
  IRAN: "IR",
  IRAQ: "IQ",
  IRELAND: "IE",
  "ISLE OF MAN": "IM",
  ISRAEL: "IL",
  ITALY: "IT",
  "IVORY COAST": "CI",
  JAMAICA: "JM",
  JAPAN: "JP",
  JERSEY: "JE",
  JORDAN: "JO",
  KAZAKHSTAN: "KZ",
  KENYA: "KE",
  KIRIBATI: "KI",
  KOSOVO: "XK",
  KUWAIT: "KW",
  KYRGYZSTAN: "KG",
  LAOS: "LA",
  LATVIA: "LV",
  LEBANON: "LB",
  LESOTHO: "LS",
  LIBERIA: "LR",
  LIBYA: "LY",
  LIECHTENSTEIN: "LI",
  LITHUANIA: "LT",
  LUXEMBOURG: "LU",
  MACAU: "MO",
  MACEDONIA: "MK",
  MADAGASCAR: "MG",
  MALAWI: "MW",
  MALAYSIA: "MY",
  MALDIVES: "MV",
  MALI: "ML",
  MALTA: "MT",
  "MARSHALL ISLANDS": "MH",
  MAURITANIA: "MR",
  MAURITIUS: "MU",
  MAYOTTE: "YT",
  MEXICO: "MX",
  MICRONESIA: "FM",
  MOLDOVA: "MD",
  MONACO: "MC",
  MONGOLIA: "MN",
  MONTENEGRO: "ME",
  MONTSERRAT: "MS",
  MOROCCO: "MA",
  MOZAMBIQUE: "MZ",
  MYANMAR: "MM",
  NAMIBIA: "NA",
  NAURU: "NR",
  NEPAL: "NP",
  NETHERLANDS: "NL",
  "NETHERLANDS ANTILLES": "AN",
  "NEW CALEDONIA": "NC",
  "NEW ZEALAND": "NZ",
  NICARAGUA: "NI",
  NIGER: "NE",
  NIGERIA: "NG",
  NIUE: "NU",
  "NORTH KOREA": "KP",
  "NORTHERN MARIANA ISLANDS": "MP",
  NORWAY: "NO",
  OMAN: "OM",
  PAKISTAN: "PK",
  PALAU: "PW",
  PALESTINE: "PS",
  PANAMA: "PA",
  "PAPUA NEW GUINEA": "PG",
  PARAGUAY: "PY",
  PERU: "PE",
  PHILIPPINES: "PH",
  PITCAIRN: "PN",
  POLAND: "PL",
  PORTUGAL: "PT",
  "PUERTO RICO": "PR",
  QATAR: "QA",
  "REPUBLIC OF THE CONGO": "CG",
  REUNION: "RE",
  ROMANIA: "RO",
  RUSSIA: "RU",
  RWANDA: "RW",
  "SAINT BARTHELEMY": "BL",
  "SAINT HELENA": "SH",
  "SAINT KITTS AND NEVIS": "KN",
  "SAINT LUCIA": "LC",
  "SAINT MARTIN": "MF",
  "SAINT PIERRE AND MIQUELON": "PM",
  "SAINT VINCENT AND THE GRENADINES": "VC",
  SAMOA: "WS",
  "SAN MARINO": "SM",
  "SAO TOME AND PRINCIPE": "ST",
  "SAUDI ARABIA": "SA",
  SENEGAL: "SN",
  SERBIA: "RS",
  SEYCHELLES: "SC",
  "SIERRA LEONE": "SL",
  SINGAPORE: "SG",
  "SINT MAARTEN": "SX",
  SLOVAKIA: "SK",
  SLOVENIA: "SI",
  "SOLOMON ISLANDS": "SB",
  SOMALIA: "SO",
  "SOUTH AFRICA": "ZA",
  "SOUTH KOREA": "KR",
  "SOUTH SUDAN": "SS",
  SPAIN: "ES",
  "SRI LANKA": "LK",
  SUDAN: "SD",
  SURINAME: "SR",
  "SVALBARD AND JAN MAYEN": "SJ",
  SWAZILAND: "SZ",
  SWEDEN: "SE",
  SWITZERLAND: "CH",
  SYRIA: "SY",
  TAIWAN: "TW",
  TAJIKISTAN: "TJ",
  TANZANIA: "TZ",
  THAILAND: "TH",
  TOGO: "TG",
  TOKELAU: "TK",
  TONGA: "TO",
  "TRINIDAD AND TOBAGO": "TT",
  TUNISIA: "TN",
  TURKEY: "TR",
  TURKMENISTAN: "TM",
  "TURKS AND CAICOS ISLANDS": "TC",
  TUVALU: "TV",
  "U.S. VIRGIN ISLANDS": "VI",
  UGANDA: "UG",
  UKRAINE: "UA",
  "UNITED ARAB EMIRATES": "AE",
  "UNITED KINGDOM": "GB",
  "UNITED STATES": "US",
  URUGUAY: "UY",
  UZBEKISTAN: "UZ",
  VANUATU: "VU",
  VATICAN: "VA",
  VENEZUELA: "VE",
  VIETNAM: "VN",
  "WALLIS AND FUTUNA": "WF",
  "WESTERN SAHARA": "EH",
  YEMEN: "YE",
  ZAMBIA: "ZM",
  ZIMBABWE: "ZW",
};

export const COUNTRY_ISO_CODE_3: { [key: string]: string } = {
  AFGHANISTAN: "AFG",
  ALBANIA: "ALB",
  ALGERIA: "DZA",
  "AMERICAN SAMOA": "ASM",
  ANDORRA: "AND",
  ANGOLA: "AGO",
  ANGUILLA: "AIA",
  ANTARCTICA: "ATA",
  "ANTIGUA AND BARBUDA": "ATG",
  ARGENTINA: "ARG",
  ARMENIA: "ARM",
  ARUBA: "ABW",
  AUSTRALIA: "AUS",
  AUSTRIA: "AUT",
  AZERBAIJAN: "AZE",
  BAHAMAS: "BHS",
  BAHRAIN: "BHR",
  BANGLADESH: "BGD",
  BARBADOS: "BRB",
  BELARUS: "BLR",
  BELGIUM: "BEL",
  BELIZE: "BLZ",
  BENIN: "BEN",
  BERMUDA: "BMU",
  BHUTAN: "BTN",
  BOLIVIA: "BOL",
  "BOSNIA AND HERZEGOVINA": "BIH",
  BOTSWANA: "BWA",
  BRAZIL: "BRA",
  "BRITISH INDIAN OCEAN TERRITORY": "IOT",
  "BRITISH VIRGIN ISLANDS": "VGB",
  BRUNEI: "BRN",
  BULGARIA: "BGR",
  "BURKINA FASO": "BFA",
  BURUNDI: "BDI",
  CAMBODIA: "KHM",
  CAMEROON: "CMR",
  CANADA: "CAN",
  "CAPE VERDE": "CPV",
  "CAYMAN ISLANDS": "CYM",
  "CENTRAL AFRICAN REPUBLIC": "CAF",
  CHAD: "TCD",
  CHILE: "CHL",
  CHINA: "CHN",
  "CHRISTMAS ISLAND": "CXR",
  "COCOS ISLANDS": "CCK",
  COLOMBIA: "COL",
  COMOROS: "COM",
  "COOK ISLANDS": "COK",
  "COSTA RICA": "CRI",
  CROATIA: "HRV",
  CUBA: "CUB",
  CURACAO: "CUW",
  CYPRUS: "CYP",
  "CZECH REPUBLIC": "CZE",
  "DEMOCRATIC REPUBLIC OF THE CONGO": "COD",
  DENMARK: "DNK",
  DJIBOUTI: "DJI",
  DOMINICA: "DMA",
  "DOMINICAN REPUBLIC": "DOM",
  "EAST TIMOR": "TLS",
  ECUADOR: "ECU",
  EGYPT: "EGY",
  "EL SALVADOR": "SLV",
  "EQUATORIAL GUINEA": "GNQ",
  ERITREA: "ERI",
  ESTONIA: "EST",
  ETHIOPIA: "ETH",
  "FALKLAND ISLANDS": "FLK",
  "FAROE ISLANDS": "FRO",
  FIJI: "FJI",
  FINLAND: "FIN",
  FRANCE: "FRA",
  "FRENCH POLYNESIA": "PYF",
  GABON: "GAB",
  GAMBIA: "GMB",
  GEORGIA: "GEO",
  GERMANY: "DEU",
  GHANA: "GHA",
  GIBRALTAR: "GIB",
  GREECE: "GRC",
  GREENLAND: "GRL",
  GRENADA: "GRD",
  GUAM: "GUM",
  GUATEMALA: "GTM",
  GUERNSEY: "GGY",
  GUINEA: "GIN",
  "GUINEA-BISSAU": "GNB",
  GUYANA: "GUY",
  HAITI: "HTI",
  HONDURAS: "HND",
  "HONG KONG": "HKG",
  HUNGARY: "HUN",
  ICELAND: "ISL",
  INDIA: "IND",
  INDONESIA: "IDN",
  IRAN: "IRN",
  IRAQ: "IRQ",
  IRELAND: "IRL",
  "ISLE OF MAN": "IMN",
  ISRAEL: "ISR",
  ITALY: "ITA",
  "IVORY COAST": "CIV",
  JAMAICA: "JAM",
  JAPAN: "JPN",
  JERSEY: "JEY",
  JORDAN: "JOR",
  KAZAKHSTAN: "KAZ",
  KENYA: "KEN",
  KIRIBATI: "KIR",
  KOSOVO: "XKX",
  KUWAIT: "KWT",
  KYRGYZSTAN: "KGZ",
  LAOS: "LAO",
  LATVIA: "LVA",
  LEBANON: "LBN",
  LESOTHO: "LSO",
  LIBERIA: "LBR",
  LIBYA: "LBY",
  LIECHTENSTEIN: "LIE",
  LITHUANIA: "LTU",
  LUXEMBOURG: "LUX",
  MACAU: "MAC",
  MACEDONIA: "MKD",
  MADAGASCAR: "MDG",
  MALAWI: "MWI",
  MALAYSIA: "MYS",
  MALDIVES: "MDV",
  MALI: "MLI",
  MALTA: "MLT",
  "MARSHALL ISLANDS": "MHL",
  MAURITANIA: "MRT",
  MAURITIUS: "MUS",
  MAYOTTE: "MYT",
  MEXICO: "MEX",
  MICRONESIA: "FSM",
  MOLDOVA: "MDA",
  MONACO: "MCO",
  MONGOLIA: "MNG",
  MONTENEGRO: "MNE",
  MONTSERRAT: "MSR",
  MOROCCO: "MAR",
  MOZAMBIQUE: "MOZ",
  MYANMAR: "MMR",
  NAMIBIA: "NAM",
  NAURU: "NRU",
  NEPAL: "NPL",
  NETHERLANDS: "NLD",
  "NETHERLANDS ANTILLES": "ANT",
  "NEW CALEDONIA": "NCL",
  "NEW ZEALAND": "NZL",
  NICARAGUA: "NIC",
  NIGER: "NER",
  NIGERIA: "NGA",
  NIUE: "NIU",
  "NORTH KOREA": "PRK",
  "NORTHERN MARIANA ISLANDS": "MNP",
  NORWAY: "NOR",
  OMAN: "OMN",
  PAKISTAN: "PAK",
  PALAU: "PLW",
  PALESTINE: "PSE",
  PANAMA: "PAN",
  "PAPUA NEW GUINEA": "PNG",
  PARAGUAY: "PRY",
  PERU: "PER",
  PHILIPPINES: "PHL",
  PITCAIRN: "PCN",
  POLAND: "POL",
  PORTUGAL: "PRT",
  "PUERTO RICO": "PRI",
  QATAR: "QAT",
  "REPUBLIC OF THE CONGO": "COG",
  REUNION: "REU",
  ROMANIA: "ROU",
  RUSSIA: "RUS",
  RWANDA: "RWA",
  "SAINT BARTHELEMY": "BLM",
  "SAINT HELENA": "SHN",
  "SAINT KITTS AND NEVIS": "KNA",
  "SAINT LUCIA": "LCA",
  "SAINT MARTIN": "MAF",
  "SAINT PIERRE AND MIQUELON": "SPM",
  "SAINT VINCENT AND THE GRENADINES": "VCT",
  SAMOA: "WSM",
  "SAN MARINO": "SMR",
  "SAO TOME AND PRINCIPE": "STP",
  "SAUDI ARABIA": "SAU",
  SENEGAL: "SEN",
  SERBIA: "SRB",
  SEYCHELLES: "SYC",
  "SIERRA LEONE": "SLE",
  SINGAPORE: "SGP",
  "SINT MAARTEN": "SXM",
  SLOVAKIA: "SVK",
  SLOVENIA: "SVN",
  "SOLOMON ISLANDS": "SLB",
  SOMALIA: "SOM",
  "SOUTH AFRICA": "ZAF",
  "SOUTH KOREA": "KOR",
  "SOUTH SUDAN": "SSD",
  SPAIN: "ESP",
  "SRI LANKA": "LKA",
  SUDAN: "SDN",
  SURINAME: "SUR",
  "SVALBARD AND JAN MAYEN": "SJM",
  SWAZILAND: "SWZ",
  SWEDEN: "SWE",
  SWITZERLAND: "CHE",
  SYRIA: "SYR",
  TAIWAN: "TWN",
  TAJIKISTAN: "TJK",
  TANZANIA: "TZA",
  THAILAND: "THA",
  TOGO: "TGO",
  TOKELAU: "TKL",
  TONGA: "TON",
  "TRINIDAD AND TOBAGO": "TTO",
  TUNISIA: "TUN",
  TURKEY: "TUR",
  TURKMENISTAN: "TKM",
  "TURKS AND CAICOS ISLANDS": "TCA",
  TUVALU: "TUV",
  "U.S. VIRGIN ISLANDS": "VIR",
  UGANDA: "UGA",
  UKRAINE: "UKR",
  "UNITED ARAB EMIRATES": "ARE",
  "UNITED KINGDOM": "GBR",
  "UNITED STATES": "USA",
  URUGUAY: "URY",
  UZBEKISTAN: "UZB",
  VANUATU: "VUT",
  VATICAN: "VAT",
  VENEZUELA: "VEN",
  VIETNAM: "VNM",
  "WALLIS AND FUTUNA": "WLF",
  "WESTERN SAHARA": "ESH",
  YEMEN: "YEM",
  ZAMBIA: "ZMB",
  ZIMBABWE: "ZWE",
};

export const ISO2_PHONE_CODE: { [key: string]: string[] } = {
  AF: ["93"],
  AL: ["355"],
  DZ: ["213"],
  AS: ["1-684"],
  AD: ["376"],
  AO: ["244"],
  AI: ["1-264"],
  AQ: ["672"],
  AG: ["1-268"],
  AR: ["54"],
  AM: ["374"],
  AW: ["297"],
  AU: ["61"],
  AT: ["43"],
  AZ: ["994"],
  BS: ["1-242"],
  BH: ["973"],
  BD: ["880"],
  BB: ["1-246"],
  BY: ["375"],
  BE: ["32"],
  BZ: ["501"],
  BJ: ["229"],
  BM: ["1-441"],
  BT: ["975"],
  BO: ["591"],
  BA: ["387"],
  BW: ["267"],
  BR: ["55"],
  IO: ["246"],
  VG: ["1-284"],
  BN: ["673"],
  BG: ["359"],
  BF: ["226"],
  BI: ["257"],
  KH: ["855"],
  CM: ["237"],
  CA: ["1"],
  CV: ["238"],
  KY: ["1-345"],
  CF: ["236"],
  TD: ["235"],
  CL: ["56"],
  CN: ["86"],
  CX: ["61"],
  CC: ["61"],
  CO: ["57"],
  KM: ["269"],
  CK: ["682"],
  CR: ["506"],
  HR: ["385"],
  CU: ["53"],
  CW: ["599"],
  CY: ["357"],
  CZ: ["420"],
  CD: ["243"],
  DK: ["45"],
  DJ: ["253"],
  DM: ["1-767"],
  DO: ["1-809", "1-829", "1-849"],
  TL: ["670"],
  EC: ["593"],
  EG: ["20"],
  SV: ["503"],
  GQ: ["240"],
  ER: ["291"],
  EE: ["372"],
  ET: ["251"],
  FK: ["500"],
  FO: ["298"],
  FJ: ["679"],
  FI: ["358"],
  FR: ["33"],
  PF: ["689"],
  GA: ["241"],
  GM: ["220"],
  GE: ["995"],
  DE: ["49"],
  GH: ["233"],
  GI: ["350"],
  GR: ["30"],
  GL: ["299"],
  GD: ["1-473"],
  GU: ["1-671"],
  GT: ["502"],
  GG: ["44-1481"],
  GN: ["224"],
  GW: ["245"],
  GY: ["592"],
  HT: ["509"],
  HN: ["504"],
  HK: ["852"],
  HU: ["36"],
  IS: ["354"],
  IN: ["91"],
  ID: ["62"],
  IR: ["98"],
  IQ: ["964"],
  IE: ["353"],
  IM: ["44-1624"],
  IL: ["972"],
  IT: ["39"],
  CI: ["225"],
  JM: ["1-876"],
  JP: ["81"],
  JE: ["44-1534"],
  JO: ["962"],
  KZ: ["7"],
  KE: ["254"],
  KI: ["686"],
  XK: ["383"],
  KW: ["965"],
  KG: ["996"],
  LA: ["856"],
  LV: ["371"],
  LB: ["961"],
  LS: ["266"],
  LR: ["231"],
  LY: ["218"],
  LI: ["423"],
  LT: ["370"],
  LU: ["352"],
  MO: ["853"],
  MK: ["389"],
  MG: ["261"],
  MW: ["265"],
  MY: ["60"],
  MV: ["960"],
  ML: ["223"],
  MT: ["356"],
  MH: ["692"],
  MR: ["222"],
  MU: ["230"],
  YT: ["262"],
  MX: ["52"],
  FM: ["691"],
  MD: ["373"],
  MC: ["377"],
  MN: ["976"],
  ME: ["382"],
  MS: ["1-664"],
  MA: ["212"],
  MZ: ["258"],
  MM: ["95"],
  NA: ["264"],
  NR: ["674"],
  NP: ["977"],
  NL: ["31"],
  AN: ["599"],
  NC: ["687"],
  NZ: ["64"],
  NI: ["505"],
  NE: ["227"],
  NG: ["234"],
  NU: ["683"],
  KP: ["850"],
  MP: ["1-670"],
  NO: ["47"],
  OM: ["968"],
  PK: ["92"],
  PW: ["680"],
  PS: ["970"],
  PA: ["507"],
  PG: ["675"],
  PY: ["595"],
  PE: ["51"],
  PH: ["63"],
  PN: ["64"],
  PL: ["48"],
  PT: ["351"],
  PR: ["1-787", "1-939"],
  QA: ["974"],
  CG: ["242"],
  RE: ["262"],
  RO: ["40"],
  RU: ["7"],
  RW: ["250"],
  BL: ["590"],
  SH: ["290"],
  KN: ["1-869"],
  LC: ["1-758"],
  MF: ["590"],
  PM: ["508"],
  VC: ["1-784"],
  WS: ["685"],
  SM: ["378"],
  ST: ["239"],
  SA: ["966"],
  SN: ["221"],
  RS: ["381"],
  SC: ["248"],
  SL: ["232"],
  SG: ["65"],
  SX: ["1-721"],
  SK: ["421"],
  SI: ["386"],
  SB: ["677"],
  SO: ["252"],
  ZA: ["27"],
  KR: ["82"],
  SS: ["211"],
  ES: ["34"],
  LK: ["94"],
  SD: ["249"],
  SR: ["597"],
  SJ: ["47"],
  SZ: ["268"],
  SE: ["46"],
  CH: ["41"],
  SY: ["963"],
  TW: ["886"],
  TJ: ["992"],
  TZ: ["255"],
  TH: ["66"],
  TG: ["228"],
  TK: ["690"],
  TO: ["676"],
  TT: ["1-868"],
  TN: ["216"],
  TR: ["90"],
  TM: ["993"],
  TC: ["1-649"],
  TV: ["688"],
  VI: ["1-340"],
  UG: ["256"],
  UA: ["380"],
  AE: ["971"],
  GB: ["44"],
  US: ["1"],
  UY: ["598"],
  UZ: ["998"],
  VU: ["678"],
  VA: ["379"],
  VE: ["58"],
  VN: ["84"],
  WF: ["681"],
  EH: ["212"],
  YE: ["967"],
  ZM: ["260"],
  ZW: ["263"],
};
